---
development:
  cloud_name: dxa6yzm41
  api_key: 738142953777974
  api_secret: NTf64lTJEEIbsF2kpTf-fGBPjRQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: my_cloud_name
  api_key: my_api_key
  api_secret: my_api_secret
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: my_cloud_name
  api_key: my_api_key
  api_secret: my_api_secret
  enhance_image_tag: true
  static_image_support: false

